In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
%matplotlib inline
# Import the API key.
from config import g_key

In [54]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df

,City_ID,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,0,Comodoro Rivadavia,0,AR,2021-11-28 19:41:45,22,-45.8667,-67.5000,75.06,28.77
1,1,Sisimiut,100,GL,2021-11-28 19:44:03,85,66.9395,-53.6735,31.21,11.50
2,2,Lebu,6,CL,2021-11-28 19:44:04,67,-37.6167,-73.6500,56.89,19.64
3,3,Port Lincoln,1,AU,2021-11-28 19:44:04,77,-34.7333,135.8667,58.89,6.06
4,4,Rikitea,12,PF,2021-11-28 19:44:04,77,-23.1203,-134.9692,76.33,16.82
5,5,Ahipara,100,NZ,2021-11-28 19:42:19,71,-35.1667,173.1667,66.34,2.21
6,6,Alice Springs,0,AU,2021-11-28 19:44:05,77,-23.7000,133.8833,56.75,0.00
7,7,Puerto Ayora,87,EC,2021-11-28 19:42:16,81,-0.7393,-90.3518,76.96,10.07
8,8,Kearney,1,US,2021-11-28 19:44:05,40,40.6995,-99.0815,56.32,20.71
9,9,Sola,39,VU,2021-11-28 19:44:06,74,-13.8833,167.5500,81.52,8.97
10,10,Ushuaia,40,AR,2021-11-28 19:41:11,66,-54.8000,-68.3000,47.86,35.68
11,11,Hay River,90,CA,2021-11-28 19:44:06,85,60.8156,-115.7999,12.18,9.22
12,12,Nouadhibou,100,MR,2021-11-28 19:44:06,64,20.9310,-17.0347,69.78,14.97
13,13,Bichena,63,ET,2021-11-28 19:44:07,56,10.4500,38.2000,52.56,1.83
14,14,Yumen,0,CN,2021-11-28 19:44:07,48,40.2833,97.2000,20.16,15.77
15,15,Mende,98,FR,2021-11-28 19:44:08,94,44.6667,3.5000,22.19,9.71
16,16,Busselton,23,AU,2021-11-28 19:44:05,85,-33.6500,115.3333,60.35,8.59
17,17,Poenari,100,RO,2021-11-28 19:44:08,89,45.3167,24.6500,53.38,2.66
18,18,Georgetown,20,MY,2021-11-28 19:41:00,88,5.4112,100.3354,76.95,0.00
19,19,Pula,40,HR,2021-11-28 19:44:09,93,44.8683,13.8481,45.46,6.91
20,20,Moussoro,25,TD,2021-11-28 19:44:09,11,13.6408,16.4901,81.61,9.75
21,21,Taltal,25,CL,2021-11-28 19:44:10,66,-25.4000,-70.4833,66.31,6.04
22,22,San Cristobal,62,VE,2021-11-28 19:44:10,52,7.7669,-72.2250,78.98,3.58
23,23,Yellowknife,90,CA,2021-11-28 19:44:11,92,62.4560,-114.3525,16.32,14.97
24,24,Mataura,94,NZ,2021-11-28 19:42:11,61,-46.1927,168.8643,53.67,2.19
25,25,Dire Dawa,5,ET,2021-11-28 19:44:11,54,9.5931,41.8661,68.05,1.88
26,26,Laerdalsoyri,0,NO,2021-11-28 19:44:12,79,61.0980,7.4816,19.72,2.30
27,27,Ottawa,75,CA,2021-11-28 19:39:29,59,45.4112,-75.6981,27.03,6.91
28,28,Kaitangata,100,NZ,2021-11-28 19:44:12,58,-46.2817,169.8464,53.85,7.56
29,29,Olga,81,RU,2021-11-28 19:43:22,55,43.7444,135.2892,34.09,4.43
...,...,...,...,...,...,...,...,...,...,...
543,543,Gilgit,67,PK,2021-11-28 19:57:42,54,35.9221,74.3087,43.30,3.27
544,544,Vestmanna,90,FO,2021-11-28 19:57:43,80,62.1564,-7.1664,34.72,0.00
545,545,Alamos,98,MX,2021-11-28 19:57:43,27,27.0167,-108.9333,81.75,2.62
546,546,Nakhon Nayok,100,TH,2021-11-28 19:57:43,68,14.1667,101.1000,80.58,5.79
547,547,Byron Bay,93,AU,2021-11-28 19:57:44,86,-28.6500,153.6167,67.95,8.77
548,548,Fuling,100,CN,2021-11-28 19:57:44,69,29.7022,107.3919,55.85,1.97
549,549,Batagay-Alyta,99,RU,2021-11-28 19:57:44,93,67.8006,130.4114,-19.07,4.09
550,550,Seydi,0,TM,2021-11-28 19:57:44,47,39.4816,62.9137,46.40,7.74
551,551,Riyadh,0,SA,2021-11-28 19:57:45,33,24.6877,46.7219,64.54,7.58
552,552,Saint Anthony,20,US,2021-11-28 19:58:45,30,45.0205,-93.2180,39.13,11.50
553,553,Oyotun,100,PE,2021-11-28 19:58:45,50,-6.8519,-79.3036,72.99,9.01
554,554,Tazovskiy,90,RU,2021-11-28 19:58:46,100,67.4667,78.7000,-14.48,5.10
555,555,Upata,84,VE,2021-11-28 19:58:46,79,8.0086,-62.3989,79.12,6.29
556,556,Eureka,79,US,2021-11-28 19:58:46,82,40.8021,-124.1637,54.21,4.70
557,557,Honiara,99,SB,2021-11-28 19:58:47,83,-9.4333,159.9500,80.19,2.24
558,558,Inhambane,0,MZ,2021-11-28 19:58:47,67,-23.8650,35.3833,71.94,11.32
559,559,Pathalgaon,100,IN,2021-11-28 19:58:47,49,22.5667,83.4667,57.87,3.49
560,560,Grand Gaube,7,MU,2021-11-28 19:58:47,71,-20.0064,57.6608,75.60,7.05
561,561,Kuusamo,40,FI,2021-11-28 19:58:48,84,65.9667,29.1833,-2.16,4.61
562,562,Rimouski,100,CA,2021-11-28 19:58:09,75,48.4488,-68.5240,28.08,19.06
563,563,Bandarbeyla,32,SO,2021-11-28 19:58:49,74,9.4942,50.8122,78.10,19.26
564,564,Sucre,63,BO,2021-11-28 19:54:58,50,-19.0333,-65.2627,69.24,24.36
565,565,Nikolayevka,100,RU,2021-11-28 19:58:49,99,53.1257,47.2041,34.52,5.59
566,566,Cabinda,20,AO,2021-11-28 19:58:49,83,-5.5500,12.2000,80.74,8.05
567,567,Paka,100,MY,2021-11-28 19:58:50,100,4.6374,103.4368,75.13,0.00
568,568,Palafrugell,13,ES,2021-11-28 19:58:50,61,41.9174,3.1631,36.36,16.20
569,569,Kafanchan,44,NG,2021-11-28 19:58:50,26,9.5833,8.3000,71.53,2.80
570,570,Quatre Cocos,4,MU,2021-11-28 19:58:51,72,-20.2078,57.7625,75.31,5.17
571,571,Nabire,96,ID,2021-11-28 19:58:51,91,-3.3667,135.4833,75.92,3.76
572,572,Zhuhai,0,CN,2021-11-28 19:58:51,73,22.2769,113.5678,69.51,12.66

In [55]:
# city_data_df.count()
city_data_df.dropna()

,City_ID,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,0,Comodoro Rivadavia,0,AR,2021-11-28 19:41:45,22,-45.8667,-67.5000,75.06,28.77
1,1,Sisimiut,100,GL,2021-11-28 19:44:03,85,66.9395,-53.6735,31.21,11.50
2,2,Lebu,6,CL,2021-11-28 19:44:04,67,-37.6167,-73.6500,56.89,19.64
3,3,Port Lincoln,1,AU,2021-11-28 19:44:04,77,-34.7333,135.8667,58.89,6.06
4,4,Rikitea,12,PF,2021-11-28 19:44:04,77,-23.1203,-134.9692,76.33,16.82
5,5,Ahipara,100,NZ,2021-11-28 19:42:19,71,-35.1667,173.1667,66.34,2.21
6,6,Alice Springs,0,AU,2021-11-28 19:44:05,77,-23.7000,133.8833,56.75,0.00
7,7,Puerto Ayora,87,EC,2021-11-28 19:42:16,81,-0.7393,-90.3518,76.96,10.07
8,8,Kearney,1,US,2021-11-28 19:44:05,40,40.6995,-99.0815,56.32,20.71
9,9,Sola,39,VU,2021-11-28 19:44:06,74,-13.8833,167.5500,81.52,8.97
10,10,Ushuaia,40,AR,2021-11-28 19:41:11,66,-54.8000,-68.3000,47.86,35.68
11,11,Hay River,90,CA,2021-11-28 19:44:06,85,60.8156,-115.7999,12.18,9.22
12,12,Nouadhibou,100,MR,2021-11-28 19:44:06,64,20.9310,-17.0347,69.78,14.97
13,13,Bichena,63,ET,2021-11-28 19:44:07,56,10.4500,38.2000,52.56,1.83
14,14,Yumen,0,CN,2021-11-28 19:44:07,48,40.2833,97.2000,20.16,15.77
15,15,Mende,98,FR,2021-11-28 19:44:08,94,44.6667,3.5000,22.19,9.71
16,16,Busselton,23,AU,2021-11-28 19:44:05,85,-33.6500,115.3333,60.35,8.59
17,17,Poenari,100,RO,2021-11-28 19:44:08,89,45.3167,24.6500,53.38,2.66
18,18,Georgetown,20,MY,2021-11-28 19:41:00,88,5.4112,100.3354,76.95,0.00
19,19,Pula,40,HR,2021-11-28 19:44:09,93,44.8683,13.8481,45.46,6.91
20,20,Moussoro,25,TD,2021-11-28 19:44:09,11,13.6408,16.4901,81.61,9.75
21,21,Taltal,25,CL,2021-11-28 19:44:10,66,-25.4000,-70.4833,66.31,6.04
22,22,San Cristobal,62,VE,2021-11-28 19:44:10,52,7.7669,-72.2250,78.98,3.58
23,23,Yellowknife,90,CA,2021-11-28 19:44:11,92,62.4560,-114.3525,16.32,14.97
24,24,Mataura,94,NZ,2021-11-28 19:42:11,61,-46.1927,168.8643,53.67,2.19
25,25,Dire Dawa,5,ET,2021-11-28 19:44:11,54,9.5931,41.8661,68.05,1.88
26,26,Laerdalsoyri,0,NO,2021-11-28 19:44:12,79,61.0980,7.4816,19.72,2.30
27,27,Ottawa,75,CA,2021-11-28 19:39:29,59,45.4112,-75.6981,27.03,6.91
28,28,Kaitangata,100,NZ,2021-11-28 19:44:12,58,-46.2817,169.8464,53.85,7.56
29,29,Olga,81,RU,2021-11-28 19:43:22,55,43.7444,135.2892,34.09,4.43
...,...,...,...,...,...,...,...,...,...,...
543,543,Gilgit,67,PK,2021-11-28 19:57:42,54,35.9221,74.3087,43.30,3.27
544,544,Vestmanna,90,FO,2021-11-28 19:57:43,80,62.1564,-7.1664,34.72,0.00
545,545,Alamos,98,MX,2021-11-28 19:57:43,27,27.0167,-108.9333,81.75,2.62
546,546,Nakhon Nayok,100,TH,2021-11-28 19:57:43,68,14.1667,101.1000,80.58,5.79
547,547,Byron Bay,93,AU,2021-11-28 19:57:44,86,-28.6500,153.6167,67.95,8.77
548,548,Fuling,100,CN,2021-11-28 19:57:44,69,29.7022,107.3919,55.85,1.97
549,549,Batagay-Alyta,99,RU,2021-11-28 19:57:44,93,67.8006,130.4114,-19.07,4.09
550,550,Seydi,0,TM,2021-11-28 19:57:44,47,39.4816,62.9137,46.40,7.74
551,551,Riyadh,0,SA,2021-11-28 19:57:45,33,24.6877,46.7219,64.54,7.58
552,552,Saint Anthony,20,US,2021-11-28 19:58:45,30,45.0205,-93.2180,39.13,11.50
553,553,Oyotun,100,PE,2021-11-28 19:58:45,50,-6.8519,-79.3036,72.99,9.01
554,554,Tazovskiy,90,RU,2021-11-28 19:58:46,100,67.4667,78.7000,-14.48,5.10
555,555,Upata,84,VE,2021-11-28 19:58:46,79,8.0086,-62.3989,79.12,6.29
556,556,Eureka,79,US,2021-11-28 19:58:46,82,40.8021,-124.1637,54.21,4.70
557,557,Honiara,99,SB,2021-11-28 19:58:47,83,-9.4333,159.9500,80.19,2.24
558,558,Inhambane,0,MZ,2021-11-28 19:58:47,67,-23.8650,35.3833,71.94,11.32
559,559,Pathalgaon,100,IN,2021-11-28 19:58:47,49,22.5667,83.4667,57.87,3.49
560,560,Grand Gaube,7,MU,2021-11-28 19:58:47,71,-20.0064,57.6608,75.60,7.05
561,561,Kuusamo,40,FI,2021-11-28 19:58:48,84,65.9667,29.1833,-2.16,4.61
562,562,Rimouski,100,CA,2021-11-28 19:58:09,75,48.4488,-68.5240,28.08,19.06
563,563,Bandarbeyla,32,SO,2021-11-28 19:58:49,74,9.4942,50.8122,78.10,19.26
564,564,Sucre,63,BO,2021-11-28 19:54:58,50,-19.0333,-65.2627,69.24,24.36
565,565,Nikolayevka,100,RU,2021-11-28 19:58:49,99,53.1257,47.2041,34.52,5.59
566,566,Cabinda,20,AO,2021-11-28 19:58:49,83,-5.5500,12.2000,80.74,8.05
567,567,Paka,100,MY,2021-11-28 19:58:50,100,4.6374,103.4368,75.13,0.00
568,568,Palafrugell,13,ES,2021-11-28 19:58:50,61,41.9174,3.1631,36.36,16.20
569,569,Kafanchan,44,NG,2021-11-28 19:58:50,26,9.5833,8.3000,71.53,2.80
570,570,Quatre Cocos,4,MU,2021-11-28 19:58:51,72,-20.2078,57.7625,75.31,5.17
571,571,Nabire,96,ID,2021-11-28 19:58:51,91,-3.3667,135.4833,75.92,3.76
572,572,Zhuhai,0,CN,2021-11-28 19:58:51,73,22.2769,113.5678,69.51,12.66

In [56]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [57]:
# # Get the maximum temperature.
# max_temp = city_data_df["Max Temp"]
# temps = []
# for temp in max_temp:
#     temps.append(max(temp, 0))

In [58]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.3)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp], dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [59]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [60]:
# Heatmap of percent cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [61]:
# Heatmap of Wind Speed
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [63]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [64]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,0,Comodoro Rivadavia,0,AR,2021-11-28 19:41:45,22,-45.8667,-67.5000,75.06,28.77
4,4,Rikitea,12,PF,2021-11-28 19:44:04,77,-23.1203,-134.9692,76.33,16.82
7,7,Puerto Ayora,87,EC,2021-11-28 19:42:16,81,-0.7393,-90.3518,76.96,10.07
9,9,Sola,39,VU,2021-11-28 19:44:06,74,-13.8833,167.5500,81.52,8.97
18,18,Georgetown,20,MY,2021-11-28 19:41:00,88,5.4112,100.3354,76.95,0.00
20,20,Moussoro,25,TD,2021-11-28 19:44:09,11,13.6408,16.4901,81.61,9.75
22,22,San Cristobal,62,VE,2021-11-28 19:44:10,52,7.7669,-72.2250,78.98,3.58
31,31,Bentiu,3,SS,2021-11-28 19:44:13,32,9.2333,29.8333,85.51,5.28
32,32,Touros,43,BR,2021-11-28 19:44:13,72,-5.1989,-35.4608,86.90,11.86
34,34,Vaini,20,TO,2021-11-28 19:43:27,73,-21.2000,-175.2000,78.96,11.50

In [65]:
preferred_cities_df.notnull().sum()

City_ID       159
City          159
Cloudiness    159
Country       158
Date          159
Humidity      159
Lat           159
Lng           159
Max Temp      159
Wind Speed    159
dtype: int64

In [66]:
preferred_cities_df.count()

City_ID       159
City          159
Cloudiness    159
Country       158
Date          159
Humidity      159
Lat           159
Lng           159
Max Temp      159
Wind Speed    159
dtype: int64

In [69]:
preferred_cities_df.isnull().sum()

City_ID       0
City          0
Cloudiness    0
Country       1
Date          0
Humidity      0
Lat           0
Lng           0
Max Temp      0
Wind Speed    0
dtype: int64

In [70]:
preferred_cities_df.dropna()

,City_ID,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,0,Comodoro Rivadavia,0,AR,2021-11-28 19:41:45,22,-45.8667,-67.5000,75.06,28.77
4,4,Rikitea,12,PF,2021-11-28 19:44:04,77,-23.1203,-134.9692,76.33,16.82
7,7,Puerto Ayora,87,EC,2021-11-28 19:42:16,81,-0.7393,-90.3518,76.96,10.07
9,9,Sola,39,VU,2021-11-28 19:44:06,74,-13.8833,167.5500,81.52,8.97
18,18,Georgetown,20,MY,2021-11-28 19:41:00,88,5.4112,100.3354,76.95,0.00
20,20,Moussoro,25,TD,2021-11-28 19:44:09,11,13.6408,16.4901,81.61,9.75
22,22,San Cristobal,62,VE,2021-11-28 19:44:10,52,7.7669,-72.2250,78.98,3.58
31,31,Bentiu,3,SS,2021-11-28 19:44:13,32,9.2333,29.8333,85.51,5.28
32,32,Touros,43,BR,2021-11-28 19:44:13,72,-5.1989,-35.4608,86.90,11.86
34,34,Vaini,20,TO,2021-11-28 19:43:27,73,-21.2000,-175.2000,78.96,11.50
37,37,Lorengau,96,PG,2021-11-28 19:44:02,81,-2.0226,147.2712,79.90,2.55
39,39,Acapulco,40,MX,2021-11-28 19:44:16,66,16.8634,-99.8901,87.62,9.22
43,43,Mahebourg,20,MU,2021-11-28 19:44:17,83,-20.4081,57.7000,75.49,3.44
44,44,Mackay,90,AU,2021-11-28 19:44:17,94,-21.1500,149.2000,75.18,4.61
47,47,Caravelas,33,BR,2021-11-28 19:45:18,92,-17.7125,-39.2481,75.27,10.45
59,59,Waingapu,100,ID,2021-11-28 19:45:22,80,-9.6567,120.2641,79.48,4.25
62,62,Awjilah,100,LY,2021-11-28 19:45:22,20,29.1081,21.2869,77.00,12.26
72,72,Carnarvon,0,AU,2021-11-28 19:45:25,64,-24.8667,113.6333,75.27,14.97
76,76,Avarua,0,CK,2021-11-28 19:42:15,65,-21.2078,-159.7750,77.05,4.61
77,77,Omboue,58,GA,2021-11-28 19:45:26,87,-1.5746,9.2618,77.34,6.73
79,79,Mecca,0,SA,2021-11-28 19:42:27,55,21.4267,39.8261,79.90,3.31
81,81,Mount Isa,75,AU,2021-11-28 19:45:27,31,-20.7333,139.5000,76.77,12.66
86,86,Tucuman,75,AR,2021-11-28 19:42:33,34,-26.8241,-65.2226,82.40,9.22
87,87,Libertador General San Martin,88,AR,2021-11-28 19:45:28,56,-23.8064,-64.7876,76.78,4.16
88,88,Hilo,1,US,2021-11-28 19:44:58,65,19.7297,-155.0900,78.53,6.91
91,91,Guarapari,77,BR,2021-11-28 19:45:29,81,-20.6667,-40.4975,76.89,1.66
93,93,Saint-Philippe,41,RE,2021-11-28 19:44:49,83,-21.3585,55.7679,76.59,3.65
101,101,Puerto Escondido,40,MX,2021-11-28 19:46:32,58,15.8500,-97.0667,86.83,5.75
105,105,Kavieng,74,PG,2021-11-28 19:44:59,79,-2.5744,150.7967,81.18,9.08
106,106,Coahuayana,0,MX,2021-11-28 19:46:33,36,18.7333,-103.6833,89.08,6.87
...,...,...,...,...,...,...,...,...,...,...
466,466,Afua,81,BR,2021-11-28 19:56:20,72,-0.1567,-50.3867,83.26,6.20
467,467,Tanout,73,NE,2021-11-28 19:56:20,12,14.9709,8.8879,77.81,9.71
476,476,Piacabucu,85,BR,2021-11-28 19:56:23,79,-10.4056,-36.4344,81.01,14.23
477,477,Tomatlan,75,MX,2021-11-28 19:56:23,44,19.9333,-105.2500,88.50,9.33
479,479,Belmonte,37,BR,2021-11-28 19:56:24,83,-15.8631,-38.8828,80.60,14.16
481,481,Finschhafen,82,PG,2021-11-28 19:56:24,75,-6.6024,147.8681,79.54,7.00
482,482,Teacapan,98,MX,2021-11-28 19:56:25,54,22.5500,-105.7500,81.27,8.61
500,500,Aloleng,41,PH,2021-11-28 19:52:43,76,16.1307,119.7824,79.47,5.70
506,506,Diu,98,IN,2021-11-28 19:57:32,46,20.7141,70.9822,75.09,8.50
509,509,Abu Zabad,3,SD,2021-11-28 19:57:32,27,12.3500,29.2500,80.33,12.68
511,511,Daru,100,PG,2021-11-28 19:57:33,80,-9.0763,143.2092,79.14,3.04
513,513,Tual,72,ID,2021-11-28 19:57:33,71,-5.6667,132.7500,83.14,2.35
525,525,Riachao Das Neves,55,BR,2021-11-28 19:57:37,72,-11.7461,-44.9100,80.89,3.49
526,526,Tegal,96,ID,2021-11-28 19:57:38,82,-6.8694,109.1402,77.02,5.19
528,528,Gamba,53,GA,2021-11-28 19:57:38,87,-2.6500,10.0000,77.63,8.32
531,531,Saint-Pierre,20,RE,2021-11-28 19:57:39,78,-21.3393,55.4781,76.68,5.75
534,534,Vanimo,100,PG,2021-11-28 19:57:40,90,-2.6741,141.3028,76.78,5.03
535,535,La Macarena,74,CO,2021-11-28 19:57:40,53,2.1837,-73.7849,88.59,6.53
536,536,Muisne,100,EC,2021-11-28 19:57:40,83,0.6000,-80.0333,82.51,12.08
539,539,Port Blair,11,IN,2021-11-28 19:57:41,74,11.6667,92.7500,79.86,7.54
545,545,Alamos,98,MX,2021-11-28 19:57:43,27,27.0167,-108.9333,81.75,2.62
546,546,Nakhon Nayok,100,TH,2021-11-28 19:57:43,68,14.1667,101.1000,80.58,5.79
555,555,Upata,84,VE,2021-11-28 19:58:46,79,8.0086,-62.3989,79.12,6.29
557,557,Honiara,99,SB,2021-11-28 19:58:47,83,-9.4333,159.9500,80.19,2.24
560,560,Grand Gaube,7,MU,2021-11-28 19:58:47,71,-20.0064,57.6608,75.60,7.05
563,563,Bandarbeyla,32,SO,2021-11-28 19:58:49,74,9.4942,50.8122,78.10,19.26
566,566,Cabinda,20,AO,2021-11-28 19:58:49,83,-5.5500,12.2000,80.74,8.05
567,567,Paka,100,MY,2021-11-28 19:58:50,100,4.6374,103.4368,75.13,0.00
570,570,Quatre Cocos,4,MU,2021-11-28 19:58:51,72,-20.2078,57.7625,75.31,5.17
571,571,Nabire,96,ID,2021-11-28 19:58:51,91,-3.3667,135.4833,75.92,3.76

In [72]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

                  City Country  Max Temp      Lat       Lng Hotel Name
0   Comodoro Rivadavia      AR     75.06 -45.8667  -67.5000
4              Rikitea      PF     76.33 -23.1203 -134.9692
7         Puerto Ayora      EC     76.96  -0.7393  -90.3518
9                 Sola      VU     81.52 -13.8833  167.5500
18          Georgetown      MY     76.95   5.4112  100.3354
20            Moussoro      TD     81.61  13.6408   16.4901
22       San Cristobal      VE     78.98   7.7669  -72.2250
31              Bentiu      SS     85.51   9.2333   29.8333
32              Touros      BR     86.90  -5.1989  -35.4608
34               Vaini      TO     78.96 -21.2000 -175.2000

In [74]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
%matplotlib inline
# Import the API key.
from config import g_key

In [75]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [91]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [92]:
hotel_df

,City,Country,Max Temp,Lat,Lng,Hotel Name
0,Comodoro Rivadavia,AR,75.06,-45.8667,-67.5000,Austral Hotel
4,Rikitea,PF,76.33,-23.1203,-134.9692,People ThankYou
7,Puerto Ayora,EC,76.96,-0.7393,-90.3518,Finch Bay Galapagos Hotel
9,Sola,VU,81.52,-13.8833,167.5500,Leumerus Bungalows
18,Georgetown,MY,76.95,5.4112,100.3354,Cititel Penang
20,Moussoro,TD,81.61,13.6408,16.4901,Hôtel Salama
22,San Cristobal,VE,78.98,7.7669,-72.2250,Posada Villaven C.A.
31,Bentiu,SS,85.51,9.2333,29.8333,Mandela hôtel
32,Touros,BR,86.90,-5.1989,-35.4608,INN NEW HORIZON
34,Vaini,TO,78.96,-21.2000,-175.2000,Keleti Beach Resort
37,Lorengau,PG,79.90,-2.0226,147.2712,Lorengau Harbourside Hotel
39,Acapulco,MX,87.62,16.8634,-99.8901,HS Hotsson Smart Acapulco
43,Mahebourg,MU,75.49,-20.4081,57.7000,Shandrani Beachcomber Resort & Spa
44,Mackay,AU,75.18,-21.1500,149.2000,International Lodge Motel
47,Caravelas,BR,75.27,-17.7125,-39.2481,Pousada dos Navegantes
59,Waingapu,ID,79.48,-9.6567,120.2641,Pondok Wisata Elim
62,Awjilah,LY,77.00,29.1081,21.2869,
72,Carnarvon,AU,75.27,-24.8667,113.6333,Hospitality Carnarvon
76,Avarua,CK,77.05,-21.2078,-159.7750,Paradise Inn
77,Omboue,GA,77.34,-1.5746,9.2618,Hotel Olako
79,Mecca,SA,79.90,21.4267,39.8261,"Makkah Clock Royal Tower, A Fairmont Hotel"
81,Mount Isa,AU,76.77,-20.7333,139.5000,ibis Styles Mt Isa Verona
86,Tucuman,AR,82.40,-26.8241,-65.2226,Dallas Hotel Tucuman
87,Libertador General San Martin,AR,76.78,-23.8064,-64.7876,Posada del Sol
88,Hilo,US,78.53,19.7297,-155.0900,Hilo Hawaiian Hotel
91,Guarapari,BR,76.89,-20.6667,-40.4975,Hotel Porto do Sol
93,Saint-Philippe,RE,76.59,-21.3585,55.7679,"Chambres d'hôte ""La Trinité"""
101,Puerto Escondido,MX,86.83,15.8500,-97.0667,Aldea del Bazar Hotel and Spa
105,Kavieng,PG,81.18,-2.5744,150.7967,Nusa Island Retreat
106,Coahuayana,MX,89.08,18.7333,-103.6833,El rranchito michuacan de ocampos
...,...,...,...,...,...,...
467,Tanout,NE,77.81,14.9709,8.8879,
476,Piacabucu,BR,81.01,-10.4056,-36.4344,Piaçabuçu News
477,Tomatlan,MX,88.50,19.9333,-105.2500,El Salvial
479,Belmonte,BR,80.60,-15.8631,-38.8828,Pousada Monte Carmelo O Pão
481,Finschhafen,PG,79.54,-6.6024,147.8681,Cossam Guest House
482,Teacapan,MX,81.27,22.5500,-105.7500,Hotel los Mangos
500,Aloleng,PH,79.47,16.1307,119.7824,Steve Walden and Emma Sison-Walden Residence
502,Keetmanshoop,NaN,77.92,-26.5833,18.1333,Quiver Inn Guesthouse
506,Diu,IN,75.09,20.7141,70.9822,Hotel Relax Inn
509,Abu Zabad,SD,80.33,12.3500,29.2500,حامد محمد نور
511,Daru,PG,79.14,-9.0763,143.2092,Daru Lodge
513,Tual,ID,83.14,-5.6667,132.7500,Grand Vilia Hotel
525,Riachao Das Neves,BR,80.89,-11.7461,-44.9100,Casa Costa
526,Tegal,ID,77.02,-6.8694,109.1402,Riez Palace Hotel
528,Gamba,GA,77.63,-2.6500,10.0000,
531,Saint-Pierre,RE,76.68,-21.3393,55.4781,Lindsey Hôtel
534,Vanimo,PG,76.78,-2.6741,141.3028,Vahmoneh Lodge Vanimo
535,La Macarena,CO,88.59,2.1837,-73.7849,Hotel Punto Verde
536,Muisne,EC,82.51,0.6000,-80.0333,Quinta Samay
539,Port Blair,IN,79.86,11.6667,92.7500,"Welcomhotel By ITC Hotels, Bay Island, Port Blair"
545,Alamos,MX,81.75,27.0167,-108.9333,Luz del Sol
546,Nakhon Nayok,TH,80.58,14.1667,101.1000,ห้างหุ้นส่วนจำกัด เอสพีรีสอร์ท
555,Upata,VE,79.12,8.0086,-62.3989,Posada Villa Nela
557,Honiara,SB,80.19,-9.4333,159.9500,Heritage Park Hotel
560,Grand Gaube,MU,75.60,-20.0064,57.6608,Veranda Paul et Virginie Hotel & Spa
563,Bandarbeyla,SO,78.10,9.4942,50.8122,JABIR HOTEL
566,Cabinda,AO,80.74,-5.5500,12.2000,Hotel Maiombe
567,Paka,MY,75.13,4.6374,103.4368,RUMBIA RESORT VILLA
570,Quatre Cocos,MU,75.31,-20.2078,57.7625,Sunrise Attitude Hotel
571,Nabire,ID,75.92,-3.3667,135.4833,Hotel Nusantara Nabire

In [94]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [96]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [97]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))